add_newline=false

format = """
[](fg:color_a)\
$os\
$username\
[](bg:color_b fg:color_a)\
$directory\
[](fg:color_b bg:color_c)\
$git_branch\
$git_status\
$character"""

palette = 'starship'
[palettes.starship]
color_success = '#33cc38'
color_error = '#cc241d'
color_text = '#d8dee9'    # Snow Storm - light gray
color_a = '#5e81ac'       # Frost - blue
color_b = '#a3be8c'       # Aurora - green
color_c = '#88c0d0'       # Frost - cyan

[os]
disabled = false
style = "bg:color_a fg:bright-white"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
format = '[ $user ](bg:color_a fg:color_text)'

[username.aliases]
"pinion" = ""
"root" = " root"   # Icon for the root user

[directory]
style = "fg:color_text bg:color_b"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_c"
format = '[[ $symbol $branch ](fg:color_text bg:color_c)]($style)'

[git_status]
style = "bg:color_c"
format = '[[($all_status$ahead_behind )](fg:color_text bg:color_c)]($style)'

[character]
disabled = false
success_symbol = '[](bold fg:color_c bg:color_success)[](bold fg:color_success)'
error_symbol = '[](bold fg:color_c bg:color_error)[](bold fg:color_error)'